<a href="https://colab.research.google.com/github/aprendizajecifuentes/Google_Colab_Ejercisios/blob/main/R_actividad_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

m1 <- matrix(1:6, nrow = 2, ncol = 3, byrow = TRUE)
print(m1)



     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6


In [ ]:
cat("\n")
m2<- matrix(1:6,nrow = 2,ncol = 3,byrow = TRUE)
print(m2)

mat<-matrix(1:9,nrow=3,byrow=TRUE)
print(mat)

cat("\n")
suma_filas<-sum(mat[1,])
print(suma_filas)
cat("\n")

traspuesta<-t(mat)
print(traspuesta)


     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9

[1] 6

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9


## **ACTIVIDAD AMTRICES**


---


23-10-2025


In [ ]:
## Creamos la matriz 3x3
notas <- matrix(1:9, nrow = 3, byrow = TRUE)
print("Creamos la matriz 3x3")
print(notas)
cat("\n")

## obtenemos el valor de fila 2, columna 3
print("obtenemos el valor de fila 2, columna 3")
f2_c3<-notas[2,3]
print(f2_c3)
cat("\n")

# Todos los elementos de la columna 1
print("Todos los elementos de la columna 1")
C1<-notas[,1]
print(C1)
cat("\n")

#Todos los elementos de la fila 3
print("Todos los elementos de la fila 3")
f3<-notas[3,]
print(f3)
cat("\n")

#La suma de la primera fila.
print("La suma de la primera fila.")
sum_f1<-sum(notas[1,])
print(sum_f1)
cat("\n")

#La transpuesta de la matriz.
print("La transpuesta de la matriz.")
T_matrix<-t(notas)
print(T_matrix)
cat("\n")

#Crea otra matriz llamada extra con los números del 10 al 18 (3x3)
# combínala con notas usando:cbind(notas, extra)

extra<- matrix(10:18,nrow=3,byrow = TRUE)
Combinada<- cbind(notas, extra)
print("Matrix combinada")
print(Combinada)





[1] "Creamos la matriz 3x3"
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9

[1] "obtenemos el valor de fila 2, columna 3"
[1] 6

[1] "Todos los elementos de la columna 1"
[1] 1 4 7

[1] "Todos los elementos de la fila 3"
[1] 7 8 9

[1] "La suma de la primera fila."
[1] 6

[1] "La transpuesta de la matriz."
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

[1] "Matrix combinada"
     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]    1    2    3   10   11   12
[2,]    4    5    6   13   14   15
[3,]    7    8    9   16   17   18
